#!/usr/bin/python
import argparse
from layer import get_extent


parser = argparse.ArgumentParser(description='Show spatial extents of a GIS file e.g .shp .geojson ')
parser.add_argument('-v', '--verbose',
	action='store_true' ,
	help='increase output verbosity' )
parser.add_argument('filename', help='the name of the file to read')

args = parser.parse_args()

if args.verbose:
	print("Opening file...")
get_extent(args.filename)
